添加client.sh客户端bash脚本,更新README
julydate/acmeDeliver pull request #3
Opened 2022-01-24 15:45 UTC by Raobee

2022-01-24 16:42 UTC, julydate requested changes
文档少了[引号](https://github.com/julydate/acmeDeliver/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R50)

另外[这里](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R37)还是改成 time.log 吧，ecc_ 是 ECC 证书的更新时间，虽然可以支持双证书部署，不过一般 RSA 证书用的多点，而且 acme.sh 的默认证书 CA 换成 zerossl 之后是不支持颁发 ECC 证书的，只有 Let's Encrypt 支持

还有 checksum 的[取值](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R11)，当服务端把 -t 参数设置的越大的时候对 checksum 的随机性就要求越高，所以默认 checksum 生成最好改成是 timestamp+random 或者取它们组合起来的 md5 值

本来计划里只是打算在客户端里实现通过传入参数把服务端指定文件下载下来而已，不过既然写了的话，把 [deployCert](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R82) 放在 checkUpdate 内下载证书成功之后调用就行，但是参照 acme.sh 的[文档](https://github.com/acmesh-official/acme.sh#3-install-the-cert-to-apachenginx-etc)来看[这里](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R63)服务端默认的文件名应该是 cert.pem 和 key.pem 还有 fullchain.pem, ca.pem 的话好像没有的样子

2022-01-24 16:45 UTC, julydate approved these changes

2022-01-25 05:39 UTC, Raobee commented
> 文档少了[引号](https://github.com/julydate/acmeDeliver/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R50)
> 
> 另外[这里](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R37)还是改成 time.log 吧，ecc_ 是 ECC 证书的更新时间，虽然可以支持双证书部署，不过一般 RSA 证书用的多点，而且 acme.sh 的默认证书 CA 换成 zerossl 之后是不支持颁发 ECC 证书的，只有 Let's Encrypt 支持
> 
> 还有 checksum 的[取值](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R11)，当服务端把 -t 参数设置的越大的时候对 checksum 的随机性就要求越高，所以默认 checksum 生成最好改成是 timestamp+random 或者取它们组合起来的 md5 值
> 
> 本来计划里只是打算在客户端里实现通过传入参数把服务端指定文件下载下来而已，不过既然写了的话，把 [deployCert](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R82) 放在 checkUpdate 内下载证书成功之后调用就行，但是参照 acme.sh 的[文档](https://github.com/acmesh-official/acme.sh#3-install-the-cert-to-apachenginx-etc)来看[这里](https://github.com/julydate/acmeDeliver/pull/3/files#diff-662a06a504d2e3e19304d896e4ddc29db7cf770539e780e96f68248e2f7e8ed3R63)服务端默认的文件名应该是 cert.pem 和 key.pem 还有 fullchain.pem, ca.pem 的话好像没有的样子

已经修复，并加入了apache,nginx的自动部署功能

2022-01-25 07:54 UTC, julydate approved these changes

2022-01-25 07:57 UTC, merged

2022-01-25 08:00 UTC, julydate commented
@Raobee 不过 manual 和 apache 部署的代码有什么区别么

另外 README 里面你修改的那版本号是展示是服务端的版本号，客户端的话你要版本号的话在 bash 里面加吧